[phases.setup]
nixPkgs = ["python311", "gcc", "python311Packages.virtualenv"]
cmds = [
  "python3 -m venv /app/venv",
  "/app/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "/app/venv/bin/python3 main.py"