[phases.setup]
nixPkgs = ["python311", "gcc", "python311Packages.pip"]
cmds = ["python3 -m ensurepip --upgrade", "python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "python3 main.py"