[phases.setup]
nixPkgs = ["python310", "gcc", "python310Packages.pip"]
cmds = ["pip install --upgrade pip", "pip install --no-cache-dir -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "python3 main.py"